apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  labels:
    app: orders-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: mo7zayed/k8s-orders-api:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - "php artisan optimize && php artisan octane:start --host=0.0.0.0 --rpc-port=6001 --port=80"
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: orders-configs
            - secretRef:
                name: orders-secrets
