apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-configs
data:
  APP_NAME: "orders-api"
  APP_ENV: "staging"
  APP_DEBUG: "true"
  APP_URL: "http://localhost:8000"

  DB_CONNECTION: "mysql"

  LOG_CHANNEL: "stack"
  LOG_LEVEL: "error"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  MAIL_MAILER: "log"

  VITE_APP_NAME: "orders-api"
